# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]

-   repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: [black==23.1.0]
        log_file: .black.log
        stages: [commit]

      - id: pylint
        name: pylint
        entry: "python lint.py --threshold=9.5 --path"
        language: python
        types: [python]
        additional_dependencies: [pylint==2.16.2]
        stages: [commit]
